extends:
  import: classic
  file: maven-bwce/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    build:
      steps:
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        # TODO: when chatops for bithub will be available
        # - comment: promote through all 'Auto' promotion Environments
        #   sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
        #   name: jx-promote
        - comment: get the service host url
          sh: echo \"REPLACE_ME_APP_NAME.jx-staging.\$(kubectl get svc --all-namespaces -o jsonpath=\'{range .items[?(@.spec.type==\"LoadBalancer\")]}{.status.loadBalancer.ingress[0].ip}\').nip.io \" > BWCEAPPURL
          name: get-serviceurl
        - comment: release the helm chart
          sh: helm upgrade --install REPLACE_ME_APP_NAME .  --set ingress.host=\$(cat BWCEAPPURL) --namespace=jx-staging
          name: helm-install
